#!/usr/bin/env bash
# This script displays the username, user id, and home directory from /etc/passwd

while IFS=: read -r username _ userid _ _ home_dir _; do
	  echo "$username:$userid:$home_dir"
  done < /etc/passwd
