#!/usr/bin/env bash
# Simulates a clock from 0:00 to 12:59

hour=0
while [ "$hour" -le 12 ]; do
  minute=0
  while [ "$minute" -le 59 ]; do
    printf "%02d:%02d\n" "$hour" "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done

