#!/usr/bin/env bash
# Checks for 'school' file and prints various messages based on its type and content

if [ -e school ]; then
  echo "school file exists"
  
  if [ -f school ]; then
    echo "school is a regular file"
  fi

  if [ -s school ]; then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi
